blank_issues_enabled: false
contact_links:
  - name: Project Support and Discussions
    url: https://github.com/orgs/newtlang/discussions
    about: Please ask and answer questions here.
  - name: Security Information
    url: https://github.com/newtlang/template?tab=security-ov-file
    about: Please report security vulnerabilities here.
